# 특성 공학 (Featrue Engineering)


In [2]:
import numpy as np
import pandas as pd

df = pd.read_csv('./perch.csv')
perch_data = df.to_numpy()

perch_weight = np.array([5.9, 32.0, 40.0, 51.5, 70.0, 100.0, 78.0, 80.0, 85.0, 85.0, 110.0,
       115.0, 125.0, 130.0, 120.0, 120.0, 130.0, 135.0, 110.0, 130.0,
       150.0, 145.0, 150.0, 170.0, 225.0, 145.0, 188.0, 180.0, 197.0,
       218.0, 300.0, 260.0, 265.0, 250.0, 250.0, 300.0, 320.0, 514.0,
       556.0, 840.0, 685.0, 700.0, 700.0, 690.0, 900.0, 650.0, 820.0,
       850.0, 900.0, 1015.0, 820.0, 1100.0, 1000.0, 1100.0, 1000.0,
       1000.0])

In [3]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(perch_data, perch_weight, random_state=42)

In [15]:
from sklearn.linear_model import LinearRegression

lr = LinearRegression()
lr.fit(X_train, y_train)
print(lr.coef_, lr.intercept_)
print(lr.score(X_train, y_train))
print(lr.score(X_test, y_test))

[ 9.07538153 69.46401443 38.00385678] -599.1708082981097
0.9559326821885706
0.8796419177546367


In [ ]:
from sklearn.preprocessing import PolynomialFeatures

poly = PolynomialFeatures(include_bias=False)
poly.fit([[2, 3, 5]])
poly.transform([[2, 3, 5]])

array([[ 2.,  3.,  5.,  4.,  6., 10.,  9., 15., 25.]])

In [17]:
poly = PolynomialFeatures(include_bias=False)
X_train_poly = poly.fit_transform(X_train)
X_test_poly = poly.fit_transform(X_test)

X_train_poly.shape, poly.get_feature_names_out()


((42, 9),
 array(['x0', 'x1', 'x2', 'x0^2', 'x0 x1', 'x0 x2', 'x1^2', 'x1 x2',
        'x2^2'], dtype=object))

In [18]:
lr_p = LinearRegression()
lr.fit(X_train_poly, y_train)

print(lr.score(X_train_poly, y_train))
print(lr.score(X_test_poly, y_test))

lr.coef_, lr.intercept_

0.9903183436982126
0.9714559911594125


(array([  34.80604039,  -88.68430232, -184.11606694,   -2.2696004 ,
           8.74890226,    9.41670602,   27.76120631, -119.89306061,
          93.68198334]),
 np.float64(124.06521772229536))

In [ ]:
poly = PolynomialFeatures(degree=5, include_bias=False)
X_train_p5 = poly.fit_transform(X_train)
X_test_p5 = poly.fit_transform(X_test)
X_train_p5.shape
# 초 과대 적합(Overfitting) -> 훈련셋에는 완벽한데, 테스트는 망한
lr.fit(X_train_p5, y_train)
lr.score(X_train_p5, y_train)
lr.score(X_test_p5, y_test)

-144.40564483377855