# `01_numpy.ipynb`

- 통계 vs 데이터분석 vs 머신러닝
    - 데이터분석: **문제를 정의하고 인사이트 도출** (고객 구매 패턴 분석)
    - 통계: 데이터를 **요약, 해석하는 수학** (평균, 분산)
    - 머신러닝: 데이터를 학습하여 **예측** (스팸함 분류, 추천)
- 데이터분석 : 데이터를 분석하여 의사결정에 도움을 준다.
    - 의사결정 데이터 기반의 근거
    - 패턴 발견, 예측 (머신 러닝)

- DA Flow (흐름)
    1. 문제 정의
    1. **데이터 수집**
    1. **데이터 정제(결측치, 이상치 처리)**
    1. **탐색 - 시각화 - 통계분석 및 해석**
    1. 결론 도출

- 시트 vs DB vs Python
    - 시트는 편함.
    - DB는 대용량 CRUD (억단위)
    - 파이썬 시각화, 분석, 머신러닝

- 라이브러리
    - `numpy`: 빠름(배열 연산) `파이썬 리스트 vs Numpy 배열 차이점`
    - `pandas`: 표(DataFrame) -> `numpy` 기반으로 만들어 짐
    - `matplotlib` : 시각화 기본(그래프)
    - `seaborn` : 시각화 심화
    - `scipy` : 고급 통계, 수학 연산
    - `scikit-learn` : 머신러닝

In [ ]:
%pip install numpy

In [ ]:
python_list = [1, 2, 3, 4, 5]
# [2, 4, 6, 8, 10]
result = [x*2 for x in python_list]
print(result)

In [ ]:
import numpy as np

array = np.array([1, 2, 3, 4, 5])
result = array * 2
print(result)

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print(arr, type(arr))
print('차원', arr.ndim)
print('형태', arr.shape)
print('크기', arr.size)

In [ ]:
arr1d = np.array([1, 2, 3, 4, 5])
arr1d

In [ ]:
l2d = [
    [1, 2, 3],
    [4, 5, 6],
]
arr2d = np.array(l2d)

arr2d.ndim, arr2d.shape, arr2d.size, arr2d.dtype

In [ ]:
# 실수형 arr
np.array([1, 2, 3], dtype=float)

In [ ]:
# 0으로 채워짐
z1d = np.zeros(5)
z2d = np.zeros((2, 3))
print(z1d)
print(z2d)

# 1로 채워짐
o1d = np.ones(5)
o2d = np.ones((2, 3))
print(o1d)
print(o2d)

# n으로 채움 -> 5칸, 7로 채움
n1d = np.full(5, 7)
n2d = np.full((2, 3), 7)
print(n1d)
print(n2d)

# 빈칸이지만 먼저 만듬
empty = np.empty(3)
print(empty)

In [ ]:
# 시퀀스 데이터

# range
range_arr = np.arange(0, 10, 2)
print(range_arr)

# 등간격 실수 배열
lin_space = np.linspace(0, 1, 5)
print(lin_space)

# *로그스케일
log_space = np.logspace(0, 2, 5)  # 10^0 ~ 10^2 5개 요소
print(log_space)

In [ ]:
# 난수 배열

# 균등 분포 난수 (0~1) 사이를 균등활률 분포
random = np.random.rand(3, 3)  # 0 ~ 1 실수
print(random)

# *정규 분포 난수
normal = np.random.randn(3, 3)
print(normal)

# 정수 난수 (0 ~ 9, 3*3)
int_random = np.random.randint(0, 10, (3, 3))
print(int_random)

# 시드 설정(랜덤 재현 가능)
np.random.seed(42)  # 랜덤 상황 42 고정
np.random.rand(3)

In [ ]:
# 배열의 데이터 타입
# 데이터 타입 확인
arr = np.array([1, 2, 3])
print(arr.dtype)

# 데이터 타입 지정 생성
f_arr = np.array([1, 2, 3], dtype=np.float64)
print(f_arr.dtype)

# 데이터 타입 변경 (int -> float)
converted = arr.astype(np.float32)
print(converted.dtype)

# 문자열 -> 숫자
str_arr = np.array(['1.2', '2.3', '3.4'])
num_arr = str_arr.astype(float)  # np.floatXX 라고 지정 안하고 float 쓰면 -> float64
print(num_arr, num_arr.dtype)

In [ ]:
# 1칸의 메모리 사용량
print(arr.itemsize)  # int64 -> 8byte
print(converted.itemsize)  # float32 -> 4byte

# 총 메모리 사용량
print(arr.nbytes)  # 8byte * 3칸
print(converted.nbytes)

In [ ]:
# 배열 재구성
arr = np.arange(12)
print(arr)

reshaped2d = arr.reshape(3, 4)  # 3row * 4col
print(reshaped2d)

reshaped3d = arr.reshape(2, 2, 3)  # 2페이지, 2row * 3col
print(reshaped3d)

# 자동계산
auto1 = arr.reshape(3, -1)  # row 3개, col 알아서
auto2 = arr.reshape(-1, 6)  # row 알아서, col 6개

print(auto1)
print(auto2)

In [ ]:
# 1차원 -> N차원
# reshape -> 원본 그대로, 새로운 배열 만드
# resize  -> 원본을 바꿈

arr = np.arange(12)
reshaped = arr.reshape(3, 4)  # 새로운 배열 리턴
print(reshaped)
print(arr)

arr.resize(3, 4)  # arr 이 바뀜
print(arr)

In [ ]:
# N차원 -> 1차원
arr = np.array([[1, 2, 3], [4, 5, 6]])

r = arr.ravel()    # 뷰(원본 연결) -> 빨리 펼쳐서 보기
f = arr.flatten()  # 복사본       -> 안전하게 새로 만들어서 활용

r[0] = 100
f[0] = -100

print(arr)
print(r, f)

In [ ]:
# 전치 -> 행과 열을 교환
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d)

arr_2d.transpose(), arr_2d.T

In [ ]:
# 1 ~ 15 정수 배열 ( arange vs array(range) )
print(np.arange(1, 16), np.array(range(1, 16)))

# 0 ~ 9까지 홀수
print(np.arange(1, 10, 2))

# 0 ~ 3까지 균등 6등분(5구간) 배열
print(np.linspace(0, 3, 6))

In [ ]:
# 4 * 4 단위 행렬(identity matrix) -> 대각선1, 나머지0
print(np.eye(4))

# 3 * 4 사이즈의 1로 가득찬 int 배열
print(np.ones((3, 4), dtype=int))

# 2 * 3 * 4 사이즈 0~1 난수 배열  
np.random.rand(2, 3, 4)      # 인자로 차원 지정 -> 오래된 버전에서 주로 씀
np.random.random((2, 3, 4))  # 튜플로 차원 지정 -> 최신 버전에서 주로 씀

## 배열의 인덱싱/슬라이싱

In [ ]:
arr = np.array([10, 20, 30, 40, 50])
# 접근
print(arr[0], arr[2], arr[-1], arr[-2])

# 변경
arr[0] = 100
print(arr)

In [ ]:
# arr_2d = np.array(range(1, 10)).reshape(3, 3)
arr_2d = np.array(
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ]
)
# Numpy 에서만 지원
arr_2d[0, 0]  # arr_2d[0][0] -> r 0, c 0
arr_2d[1, 1]

arr_2d[1]  # 행 접근

# 변경
arr_2d[0, 0] = 100
arr_2d


In [ ]:
# 슬라이싱
arr = np.arange(10)
print(
    arr[2:5],
    arr[:5],
    arr[5:]
)

print(
    arr[1:8:2],
    arr[::2]
)

print(
    arr[::-1],
    arr[7:2:-1]
)

# 슬라이싱으로 일괄 변경 (Python X)
arr[3:6] = 100
print(arr)

In [ ]:
# 다차원 배열 슬라이싱
arr_2d = np.arange(1, 13).reshape(3, -1)
print(arr_2d)

# row(행) 슬라이싱 -> 0, 1 idx 행
print(arr_2d[0:2])

# col(열) 슬라이싱 -> 모든 행의 idx 1, 2 열
print(arr_2d[:, 1:3])

# row / col 동시 슬라이싱 -> 1, 2 행 / 0, 1 열 
print(arr_2d[1:3, 0:2])

# 간격지정  -> 행/열 모두 2간격
print(arr_2d[::2, ::2])  

In [ ]:
# 다차원 배열 슬라이싱으로 변경
print(arr_2d)

# 부분 배열 일괄 변경
arr_2d[0:2, 0:2] = 0
print(arr_2d)

# 열 교체 (모든행, idx 3열) -> 벡터 ->  교체 -> 원본 matrix 의 열이 바뀜
arr_2d[:, 3] = [100, 200, 300]

print(arr_2d)


In [ ]:
# boolean 인덱싱
# 조건에 따라 배열 요소 선택

arr = np.arange(1, 6)  # [1, 2, 3, 4, 5]

# 마스킹 -> T/F 로 바꿈
mask = arr > 3
print(mask, arr)

# 마스킹 배열로 필터링
print(arr[mask])

# 직접 조건
print(arr[arr > 3])

# 다중조건
print(arr[ (arr > 2) & (arr < 5) ])  # and
print(arr[ (arr == 1) | (arr > 3) ])  # or

In [ ]:
# 2차원 배열 불리언 인덱싱
arr_2d = np.arange(1, 10).reshape(3, 3)

mask = arr_2d > 5

# 원본 matrix 형태 없음. True 로 필터된 애들만 Vector로 나옴
print(arr_2d[mask])  
print(arr_2d[arr_2d < 6])

# 조건에 맞는 행만 선택
row_mask = np.array([True, False, True])
print(arr_2d)
print(arr_2d[row_mask])  # row T, F, T -> 0, 2 row 만 뽑음


In [ ]:
# Fancy 인덱싱
arr = np.arange(10, 60, 10)
print(arr)
# arr[1, 2]  -> arr[1][2]
print(arr[ [1, 2] ])  # -> arr[1], arr[2] 를 뽑아라
print(arr[ [0, 2, 3] ])  # -> arr[0], arr[2], arr[3] 만 가져와라

print(arr[[0, 0, 1, 1, 2, 3, 4, 2, 1]])
print(arr[[4, 2, 3, 1, 0]])


In [ ]:
arr_2d = np.arange(1, 10).reshape(3, 3)
print(arr_2d)

print(arr_2d[0])  # row 0

# 특정 행만 선택
print(arr_2d[ [0, 2] ])  # row 0, 2

print()

# 행과, 열 동시에 선택
print(
    arr_2d[  # (0, 0), (1, 2), (2, 1) 순서로 벡터 만듬
        [0, 1, 2],
        [0, 2, 1]
    ]
)

# 행렬의 열을 순서 바꾸기
print(
    arr_2d[
        :,         # 모든 행
        [2, 0, 1]  # 열 idx를 이렇게 바꿔라
    ]
)

In [ ]:
# 10부터 20까지의 정수 배열 생성
arr = np.arange(10, 21)
print('원본', arr)

# 문제1: 배열의 첫 번째, 세 번째, 마지막 요소 출력
print(
    arr[0],
    arr[2],
    arr[-1]
)

# 문제2: 인덱스 2부터 5까지 요소 출력
print(arr[2:6])

# 문제3: 처음부터 5번째 요소까지 모든 짝수 인덱스 요소 출력
print(arr[0:6:2])

# 문제4: 배열의 요소를 역순으로 출력
print(arr[::-1])


In [ ]:
# 3 * 4 matrix
matrix = np.arange(12).reshape(3, 4)
print('원본', matrix)

# 문제1: (1,2) 위치의 요소 출력
print(matrix[1, 2])  # matrix[1][2]

# 문제2: 두 번째 행 전체 출력
matrix[1]

# 문제3: 마지막 열 전체 출력
matrix[:, -1] 

# 문제4: 첫 번째와 세 번째 행의 두 번째와 네 번째 열 요소만 추출
matrix[[0, 2], :][:, [1, 3]]  # matrix[np.ix_([0, 2], [1, 3])]

In [ ]:
arr = np.arange(1, 21)
print('원본', arr)

# 문제1: 5의 배수만 선택하여 출력
print(arr[arr % 5 == 0])
# 문제2: 3보다 크고 15보다 작은 요소 선택
print(arr[(arr>3) & (arr < 15)])
# 문제3: 7의 배수이거나 홀수인 요소 선택
print(arr[(arr%7==0) | (arr%2==1)])

In [ ]:
matrix = np.arange(1, 21).reshape(5, 4)
print('원본', matrix)

# 문제4: 10보다 큰 요소만 100으로 변경 (슬라이싱/불리언인덱싱 -> 뷰 생성 (원본데이터 연결))
print(matrix[matrix>10])
matrix[matrix>10] = 100
print(matrix)

## 선형대수 연산

### 배열 <-> 배열 연산

In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

print(a + b)
print(a - b)
print(a * b)
print(a / b)

print(a ** 2)
print(a ** b)

In [ ]:
a = np.array([True, False, True, False])
b = np.array([False, True, True, False])

# 논리연산
# AND
print(a & b)
# OR
print(a | b)
# NOT
print(~a)

### 벡터(1줄) <-> 스칼라(단일값) 연산
> Broadcasting (스칼라가 배열 크기에 맞게 확장)

In [ ]:
# 배열 생성
arr = np.array([1, 2, 3, 4, 5])

# 스칼라 덧셈
print(arr + 10)     # [11 12 13 14 15]

# 스칼라 뺄셈
print(arr - 1)      # [0 1 2 3 4]

# 스칼라 곱셈
print(arr * 2)      # [2 4 6 8 10]

# 스칼라 나눗셈
print(arr / 2)      # [0.5 1.  1.5 2.  2.5]

# 스칼라 거듭제곱
print(arr ** 2)     # [ 1  4  9 16 25]

# 스칼라 비교 (불리언 배열)
print(arr > 3)      # [False False False  True  True]
print(arr == 2)     # [False  True False False False]

### 매트릭스(행렬) <-> 스칼라(단일값) 연산

In [ ]:
# 2차원 배열
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

# 스칼라 연산
print(arr_2d + 10)

print(arr_2d * 3)

### 매트릭스(행렬) <-> 벡터(1줄) 연산

In [ ]:
matrix = np.array([[1, 2, 3], [4, 5, 6]])
vector = np.array([10, 20, 30])

# 행렬 + 행 벡터
print(matrix + vector)

# 열 벡터 브로드캐스팅
col_vec = np.array(
    [
        [100],
        [200]
    ]
)
print(matrix + col_vec)

In [ ]:
matrix = np.array([[1, 2, 3], [4, 5, 6]])
vector = np.array([10, 20, 30])

print('Matrix shape', matrix.shape)
print('Vector shape', vector.shape)
# 1. Vector(3,  ) 가 앞에 1이 추가됨. -> Matrix (1, 3) 으로 변함.
# 2. 더해야하는 matrix(2, 3)이랑 줄수가 같을때 까지 row 복사함.
print('Matrix + Vector')
print(matrix + vector)

In [ ]:
# 브로드 캐스팅 가능한 경우 (Shape 확인을 하자!)

A = np.ones((3, 2))       # 3x2 배열
B = np.ones((2,))         # 길이 2인 1차원 배열 (1x2로 해석) (행벡터)
C = np.ones((3, 1))       # 3x1 배열 (사실상 열벡터)

print("A + B 형태:", (A + B).shape)  # (3, 2) - B는 각 행에 브로드캐스팅
print(A + B)


print("A + C 형태:", (A + C).shape)  # (3, 2) - C는 각 열에 브로드캐스팅
print(A + C)

In [ ]:
# 뷰(원본 데이터와 링크) 와 복사본(완전 별도) 차이
arr = np.arange(1, 6)
print(arr)

# 슬라이싱 -> 뷰 생성
view = arr[1:4]
print(view)

view[0] = 20
print(arr)

# 복사본..?
copy = arr.copy()
copy[0] = 100
print(arr, copy)

In [ ]:
# 연산중 데이터 자동 변환
int_arr = np.array([1, 2, 3])
float_arr = np.array([1.5, 2.5, 3.5])

# int + float = float
print(int_arr + float_arr)

# int / int = float
print(int_arr / 2)

# int // int = int
print(int_arr // 2)

In [ ]:
arr1 = np.array([8, 12, 6, 10])
arr2 = np.array([3, 4,  1, 20])

print(arr1 ** 2)
print(arr1 ** 0.5, np.sqrt(arr1))  # 루트. 같은 결과

# 각 자리마다 최대값만 모음
print(np.maximum(arr1, arr2))

# arr1 + arr2 의 모든 자리수를 더한 총합
print(np.sum(arr1 + arr2))

In [ ]:
# 테스트 배열
x = np.array([0, np.pi/4, np.pi/2, np.pi])
y = np.array([1, 2, 3, 4])

# 삼각함수
print("sin(x) =", np.sin(x))  # [0., 0.70710678, 1., 0.]
print("cos(x) =", np.cos(x))  # [1., 0.70710678, 0., -1.]
print("tan(x) =", np.tan(x))  # [0., 1., 16331239353195370., 0.]

# 역삼각함수
print("arcsin(sin(x)) =", np.arcsin(np.sin(x)))

# 지수와 로그 

# 자연상수 e^x -> e^1, e^2, e^3, e^4
print("exp(y) =", np.exp(y))  # [2.71828183, 7.3890561, 20.08553692, 54.59815003]
# 자연상수 log e
print("log(y) =", np.log(y))  # [0., 0.69314718, 1.09861229, 1.38629436]
print("log10(y) =", np.log10(y))  # [0., 0.30103, 0.47712125, 0.60205999]
print("log2(y) =", np.log2(y))  # [0., 1., 1.58496250, 2.]

# 제곱근과 거듭제곱
print("sqrt(y) =", np.sqrt(y))  # [1., 1.41421356, 1.73205081, 2.]
print("power(y, 2) =", np.power(y, 2))  # [1, 4, 9, 16]
print("power(y, 3) =", np.power(y, 3))  # [1, 8, 27, 64]

# 절대값과 부호
z = np.array([-2, -1, 0, 1, 2])
print("abs(z) =", np.abs(z))  # [2 1 0 1 2]
print("sign(z) =", np.sign(z))  # [-1 -1  0  1  1]

# 소수점 처리
w = np.array([1.2, 2.7, 3.5, 4.9])
print("floor(w) =", np.floor(w))  # [1. 2. 3. 4.] (내림)
print("ceil(w) =", np.ceil(w))   # [2. 3. 4. 5.] (올림)
print("round(w) =", np.round(w))  # [1. 3. 4. 5.] (반올림)
print("trunc(w) =", np.trunc(w))  # [1. 2. 3. 4.] (소수점 버림)

In [ ]:
arr = np.array([
    [1, 2, 3], 
    [4, 5, 6], 
    [7, 8, 9]
])

# 기본 집계
print("합계:", np.sum(arr))          # 45
print("평균:", np.mean(arr))         # 5.0
print("최소값:", np.min(arr))        # 1
print("최대값:", np.max(arr))        # 9
print("표준편차:", np.std(arr))      # 2.581988897471611
print("분산:", np.var(arr))          # 6.666666666666667

# 축을 따라 집계
print("행별 합계:", np.sum(arr, axis=1))  # [ 6 15 24]
print("열별 합계:", np.sum(arr, axis=0))  # [12 15 18]
print("행별 평균:", np.mean(arr, axis=1))  # [2. 5. 8.]
print("열별 평균:", np.mean(arr, axis=0))  # [4. 5. 6.]
print("행별 최소값:", np.min(arr, axis=1))  # [1 4 7]
print("열별 최소값:", np.min(arr, axis=0))  # [1 2 3]

In [ ]:
arr = np.array([
    [1, 2, 3], 
    [4, 5, 6], 
    [7, 8, 9]
])

# 누적 합계 (cumulative sum)
print("누적 합계:", np.cumsum(arr))  # [ 1  3  6 10 15 21 28 36 45]
print("행별 누적 합계:")
print(np.cumsum(arr, axis=1))
# [[ 1  3  6]
#  [ 4  9 15]
#  [ 7 15 24]]

# 누적 곱 (cumulative product)
print("누적 곱:", np.cumprod(arr))  # [1 2 6 24 120 720 5040 40320 362880]

# 중앙값 (median)
print("중앙값:", np.median(arr))        # 5.0
print("행별 중앙값:", np.median(arr, axis=1))  # [2. 5. 8.]
print("열별 중앙값:", np.median(arr, axis=0))  # [4. 5. 6.]

# 백분위수 (percentile)
print("25% 백분위수:", np.percentile(arr, 25))  # 3.0
print("50% 백분위수:", np.percentile(arr, 50))  # 5.0 (중앙값과 동일)
print("75% 백분위수:", np.percentile(arr, 75))  # 7.0

# 가중 평균 (weighted average)
weights = np.array([0.1, 0.3, 0.6])  # 가중치
data = np.array([2, 5, 8])
print("가중 평균:", np.average(data, weights=weights))  # 6.5 

In [ ]:
# 배열 분할
# 샘플 배열
arr = np.arange(12)  # [ 0  1  2  3  4  5  6  7  8  9 10 11]

# 균등 분할
print("3개로 균등 분할:")
print(np.split(arr, 3))  # [array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]

# 위치 지정 분할
print("위치 지정 분할 (인덱스 3, 8 기준):")
print(np.split(arr, [3, 8]))  # [array([0, 1, 2]), array([3, 4, 5, 6, 7]), array([ 8,  9, 10, 11])]

# 2차원 배열 분할
arr_2d = np.arange(16).reshape(4, 4)
print("2차원 배열:")
print(arr_2d)

# 행 방향 분할
print("행 방향 분할:")
print(np.split(arr_2d, 2, axis=0))  # 2개 배열로 (각 2x4)
print(np.vsplit(arr_2d, 2))  # 동일한 결과

# 열 방향 분할
print("열 방향 분할:")
print(np.split(arr_2d, 2, axis=1))  # 2개 배열로 (각 4x2)
print(np.hsplit(arr_2d, 2))  # 동일한 결과

In [ ]:
# 1차원 배열 결합
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = np.concat( (arr1, arr2) )  # np.concatenate 도 같음
print(result)

# 2차원 배열 결합
arr2d1 = np.array([ [1, 2], [3, 4] ])
arr2d2 = np.array([ [5, 6], [7, 8] ])

# concat, axis=0 == vstack
result2 = np.concat( (arr2d1, arr2d2), axis=0)
result22 = np.vstack( (arr2d1, arr2d2) )
print(result2)
print(result22)
# concat, axis=1 == hstack
result3 = np.concat( (arr2d1, arr2d2), axis=1)
result33 = np.hstack( (arr2d1, arr2d2) )
print(result3)

# matrix 두개를 겹친다 => Tensor
result4 = np.dstack( (arr2d1, arr2d2) )
print(result4)

In [ ]:
# 벡터를 차원 확장 (행이냐 열이냐)
arr = np.array([1, 2, 3, 4])
print(arr)

# row vector -> [ [1 2 3 4] ]
row_vector = np.expand_dims(arr, axis=0)
print(row_vector)
row_vector2 = arr[np.newaxis, :]
print(row_vector2)

# col vector -> [ [1] [2] [3] [4] ]
col_vector = np.expand_dims(arr, axis=1)
print(col_vector)
col_vector2 = arr[:, np.newaxis]
print(col_vector2)

In [ ]:
# 차원 축소
arr = np.array([ [ [1], [2], [3] ] ])
print(arr, arr.shape)

# 모든 단일차원(shape에서 1 나온 것들) 제거
print(np.squeeze(arr))  #  [1 2 3]

# 특정 축만 제거
arr2 = np.array([ [ [ 1, 2, 3 ] ] ])
print(arr2, arr2.shape)  # 1 1 3

print(np.squeeze(arr2, axis=1))  # 1 3 

In [ ]:
# 학급별 시험 점수 (5개 학급, 각 10명의 학생)
scores = np.random.randint(50, 101, size=(5, 10))  # 50~100 사이 점수
print("학급별 점수:")
print(scores)

# 문제1: 전체 평균과 표준편차
print("전체 평균:", np.mean(scores))
print("전체 표준편차:", np.std(scores))
print("전체 중앙값:", np.median(scores))

# 문제2: 학급별 최고점과 최저점
print("학급별 최고점:", np.max(scores, axis=1))
print("학급별 최저점:", np.min(scores, axis=1))

# 문제3: 전체 학생 중 상위 25%와 하위 25% 컷오프 점수
print("상위 25% 컷오프:", np.percentile(scores, 75))
print("하위 25% 컷오프:", np.percentile(scores, 25))

# 문제4: 학급별 평균이 가장 높은/낮은 학급 찾기
class_means = np.mean(scores, axis=1)
print("학급별 평균:", class_means)
print("최고 평균 학급:", np.argmax(class_means) + 1)  # +1은 학급 번호 조정
print("최저 평균 학급:", np.argmin(class_means) + 1)  # +1은 학급 번호 조정

## 유틸리티 함수

In [ ]:
# where
arr = np.arange(10)

# 단순 필터링 (짝수)
print(np.where(arr % 2 == 0))
# 값을 바꾸기
print(np.where(arr % 2 == 0, '짝수', '홀수'))

# 0 ~ 10 랜덤으로 3 x 3
arr2d = np.random.randint(0, 10, (3, 3))
print(arr2d)

# 조건만 걸면, 좌표(인덱스)가 나옴
print(np.where(arr2d > 5))
# 5보다 큰 값들은 *2, 아니면 그대로
print(np.where(arr2d > 5, arr2d * 2, arr2d))
# 그냥 조건에 맞는 값들만 보고싶으면?
print(arr2d[arr2d > 5])

In [ ]:
# argmax, argmin

# 벡터에서 최대/최소 위치
arr = np.array([3, 5, 1, 0, 4])

max_idx = np.argmax(arr)
min_idx = np.argmin(arr)

print(max_idx, min_idx)

# 매트릭스에서 최대/최소
np.random.seed(23)
arr2d = np.random.randint(0, 10, (3, 3))
print(arr2d)

# 각 행에서 최대값의 idx
row_max = np.argmax(arr2d, axis=1)
print(row_max)
# 각 열에서 최소값의 idx
col_min = np.argmin(arr2d, axis=0)
print(col_min)

In [ ]:
# unique 고유값 찾기 
arr = np.array([1,2,3,2,3,4,3,1,5,5,6,4])

# 값들만
unique_values = np.unique(arr)
print(unique_values)

# 값들, 개수
values, count = np.unique(arr, return_counts=True)
print('values', values)
print('count:', count)

# 값들, 개수 -> dict
freq_dict = dict(zip(values, count))
print(freq_dict)

# 가장 많이 등장하는 숫자 찾기
idx = np.argmax(count)
print('가장많이나온숫자', values[idx])

In [ ]:
arr = np.array([3, 5, 1, 0, 4, 2, 7])

# 오름차순 정렬 ASC
print(np.sort(arr))

# 내림차순 정렬 DESC
print(np.sort(arr)[::-1])

# 정렬하기 위한 인덱스 배치
idx = np.argsort(arr)
print(idx)
print(arr[idx])

In [ ]:
# Matrix 정렬 
np.random.seed(1)
arr2d = np.random.randint(0, 10, (3, 4))
print(arr2d)

# 행별 asc 정렬
row_sorted = np.sort(arr2d, axis=1)
print(row_sorted)

# 열별 desc 정렬
col_sorted = np.sort(arr2d, axis=0)[::-1]
print(col_sorted)

## 실습

In [ ]:
# 가상의 학생 시험 점수 데이터
math_scores = np.array([85, 90, 75, 95, 70, 80, 65, 75, 90, 85])
science_scores = np.array([90, 85, 80, 95, 70, 75, 65, 80, 85, 90])
english_scores = np.array([80, 85, 90, 80, 75, 90, 70, 75, 85, 95])

subjects = ['수학', '과학', '영어']
scores = np.vstack((math_scores, science_scores, english_scores))

In [150]:
# 기본 통계 (과목별 평균, 중앙값, 표준편차, 최소, 최대)
for idx, subject in enumerate(scores):
    # 평균 mean
    mean_score = np.mean(subject)
    # 중앙값 median
    median_score = np.median(subject)
    # 표준편차 standard devieation (std)
    std_dev = np.std(subject)
    # 최소 min
    min_score = np.min(subject)
    # 최대 max
    max_score = np.max(subject)

    print(f'{subjects[idx]} 평균: {mean_score:.2f}, 중앙값: {median_score},',
          f'표준편차: {std_dev:.3f} 최소: {min_score}, 최대: {max_score}')

수학 평균: 81.00, 중앙값: 82.5, 표준편차: 9.165 최소: 65, 최대: 95
과학 평균: 81.50, 중앙값: 82.5, 표준편차: 8.958 최소: 65, 최대: 95
영어 평균: 82.50, 중앙값: 82.5, 표준편차: 7.500 최소: 70, 최대: 95


In [169]:
# 총점 기준 상위 3명 학생의 정보 표시 
# | 학생번호(idx) | 수학 | 과학 | 영어 | 총점 |

# 과목 총점 배열
total_scores = np.sum(scores, axis=0)
print(total_scores)
# 총점 desc 정렬 후 3명 잘라서 idx만 내놔
top_students = np.argsort(total_scores)[::-1][:3]

print('학생번호 | 수학 | 과학 | 영어 | 총점')
for idx in top_students:
    print(
        f'{idx+1:^7} | {math_scores[idx]:^3} | {science_scores[idx]:^4} |',
        f'{english_scores[idx]:^3} | {total_scores[idx]}'
    )

[255 260 245 270 215 245 200 230 260 270]
학생번호 | 수학 | 과학 | 영어 | 총점
  10    | 85  |  90  | 95  | 270
   4    | 95  |  95  | 80  | 270
   9    | 90  |  85  | 85  | 260


In [171]:
# 과목별 상관관계

correlation = np.corrcoef(scores)
print("과목 간 상관관계:")
for i in range(3):
    for j in range(i+1, 3):
        print(f"{subjects[i]}-{subjects[j]} 상관계수: {correlation[i, j]:.4f}")

과목 간 상관관계:
수학-과학 상관계수: 0.8952
수학-영어 상관계수: 0.4728
과학-영어 상관계수: 0.4651
