# `01_numpy.ipynb`

- 통계 vs 데이터분석 vs 머신러닝
    - 데이터분석: **문제를 정의하고 인사이트 도출** (고객 구매 패턴 분석)
    - 통계: 데이터를 **요약, 해석하는 수학** (평균, 분산)
    - 머신러닝: 데이터를 학습하여 **예측** (스팸함 분류, 추천)
- 데이터분석 : 데이터를 분석하여 의사결정에 도움을 준다.
    - 의사결정 데이터 기반의 근거
    - 패턴 발견, 예측 (머신 러닝)

- DA Flow (흐름)
    1. 문제 정의
    1. **데이터 수집**
    1. **데이터 정제(결측치, 이상치 처리)**
    1. **탐색 - 시각화 - 통계분석 및 해석**
    1. 결론 도출

- 시트 vs DB vs Python
    - 시트는 편함.
    - DB는 대용량 CRUD (억단위)
    - 파이썬 시각화, 분석, 머신러닝

- 라이브러리
    - `numpy`: 빠름(배열 연산) `파이썬 리스트 vs Numpy 배열 차이점`
    - `pandas`: 표(DataFrame) -> `numpy` 기반으로 만들어 짐
    - `matplotlib` : 시각화 기본(그래프)
    - `seaborn` : 시각화 심화
    - `scipy` : 고급 통계, 수학 연산
    - `scikit-learn` : 머신러닝

In [ ]:
%pip install numpy

In [ ]:
python_list = [1, 2, 3, 4, 5]
# [2, 4, 6, 8, 10]
result = [x*2 for x in python_list]
print(result)

In [ ]:
import numpy as np

array = np.array([1, 2, 3, 4, 5])
result = array * 2
print(result)

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print(arr, type(arr))
print('차원', arr.ndim)
print('형태', arr.shape)
print('크기', arr.size)

In [ ]:
arr1d = np.array([1, 2, 3, 4, 5])
arr1d

In [21]:
l2d = [
    [1, 2, 3],
    [4, 5, 6],
]
arr2d = np.array(l2d)

arr2d.ndim, arr2d.shape, arr2d.size, arr2d.dtype

(2, (2, 3), 6, dtype('int64'))

In [19]:
# 실수형 arr
np.array([1, 2, 3], dtype=float)

array([1., 2., 3.])

In [ ]:
# 0으로 채워짐
z1d = np.zeros(5)
z2d = np.zeros((2, 3))
print(z1d)
print(z2d)

# 1로 채워짐
o1d = np.ones(5)
o2d = np.ones((2, 3))
print(o1d)
print(o2d)

# n으로 채움 -> 5칸, 7로 채움
n1d = np.full(5, 7)
n2d = np.full((2, 3), 7)
print(n1d)
print(n2d)

# 빈칸이지만 먼저 만듬
empty = np.empty(3)
print(empty)

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]
[7 7 7 7 7]
[[7 7 7]
 [7 7 7]]
[1. 2. 3.]


In [ ]:
# 시퀀스 데이터

# range
range_arr = np.arange(0, 10, 2)
print(range_arr)

# 등간격 실수 배열
lin_space = np.linspace(0, 1, 5)
print(lin_space)

# *로그스케일
log_space = np.logspace(0, 2, 5)  # 10^0 ~ 10^2 5개 요소
print(log_space)

[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
[  1.           3.16227766  10.          31.6227766  100.        ]


In [61]:
# 난수 배열

# 균등 분포 난수 (0~1) 사이를 균등활률 분포
random = np.random.rand(3, 3)  # 0 ~ 1 실수
print(random)

# *정규 분포 난수
normal = np.random.randn(3, 3)
print(normal)

# 정수 난수 (0 ~ 9, 3*3)
int_random = np.random.randint(0, 10, (3, 3))
print(int_random)

# 시드 설정(랜덤 재현 가능)
np.random.seed(42)  # 랜덤 상황 42 고정
np.random.rand(3)

[[0.43532239 0.4203678  0.33033482]
 [0.20464863 0.61927097 0.29965467]
 [0.26682728 0.62113383 0.52914209]]
[[ 0.04153939 -1.11792545  0.53905832]
 [-0.5961597  -0.0191305   1.17500122]
 [-0.74787095  0.00902525 -0.87810789]]
[[0 4 2]
 [4 1 7]
 [8 2 9]]


array([0.37454012, 0.95071431, 0.73199394])

In [71]:
# 배열의 데이터 타입
# 데이터 타입 확인
arr = np.array([1, 2, 3])
print(arr.dtype)

# 데이터 타입 지정 생성
f_arr = np.array([1, 2, 3], dtype=np.float64)
print(f_arr.dtype)

# 데이터 타입 변경 (int -> float)
converted = arr.astype(np.float32)
print(converted.dtype)

# 문자열 -> 숫자
str_arr = np.array(['1.2', '2.3', '3.4'])
num_arr = str_arr.astype(float)  # np.floatXX 라고 지정 안하고 float 쓰면 -> float64
print(num_arr, num_arr.dtype)

int64
float64
float32
[1.2 2.3 3.4] float64


In [ ]:
# 1칸의 메모리 사용량
print(arr.itemsize)  # int64 -> 8byte
print(converted.itemsize)  # float32 -> 4byte

# 총 메모리 사용량
print(arr.nbytes)  # 8byte * 3칸
print(converted.nbytes)

8
4
24
12


In [ ]:
# 배열 재구성
arr = np.arange(12)
print(arr)

reshaped2d = arr.reshape(3, 4)  # 3row * 4col
print(reshaped2d)

reshaped3d = arr.reshape(2, 2, 3)  # 2페이지, 2row * 3col
print(reshaped3d)

# 자동계산
auto1 = arr.reshape(3, -1)  # row 3개, col 알아서
auto2 = arr.reshape(-1, 6)  # row 알아서, col 6개

print(auto1)
print(auto2)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [83]:
# reshape -> 원본 그대로, 새로운 배열 만드
# resize  -> 원본을 바꿈

arr = np.arange(12)
reshaped = arr.reshape(3, 4)  # 새로운 배열 리턴
print(reshaped)
print(arr)

arr.resize(3, 4)  # arr 이 바뀜
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [90]:
# 1 ~ 15 정수 배열 ( arange vs array(range) )
print(np.arange(1, 16), np.array(range(1, 16)))

# 0 ~ 9까지 홀수
print(np.arange(1, 10, 2))

# 0 ~ 3까지 균등 6등분(5구간) 배열
print(np.linspace(0, 3, 6))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15] [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[1 3 5 7 9]
[0.  0.6 1.2 1.8 2.4 3. ]


In [ ]:
# 4 * 4 단위 행렬(identity matrix) -> 대각선1, 나머지0
print(np.eye(4))

# 3 * 4 사이즈의 1로 가득찬 int 배열
np.ones((3, 4), dtype=int)

# 2 * 3 * 4 사이즈 0~1 난수 배열  
np.random.rand(2, 3, 4)      # 인자로 차원 지정 -> 오래된 버전에서 주로 씀
np.random.random((2, 3, 4))  # 튜플로 차원 지정 -> 최신 버전에서 주로 씀

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


array([[[0.51423444, 0.59241457, 0.04645041, 0.60754485],
        [0.17052412, 0.06505159, 0.94888554, 0.96563203],
        [0.80839735, 0.30461377, 0.09767211, 0.68423303]],

       [[0.44015249, 0.12203823, 0.49517691, 0.03438852],
        [0.9093204 , 0.25877998, 0.66252228, 0.31171108],
        [0.52006802, 0.54671028, 0.18485446, 0.96958463]]])